services:
  fastapi:
    build: .
    container_name: teryt_api
    command: uvicorn main:app --host 0.0.0.0 --port 5555
    ports:
      - "5555:5555"
    volumes:
      - ./dane:/app/dane
    restart: unless-stopped
